/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as FigmaIndexRouteImport } from './routes/figma/index'
import { Route as BasicIndexRouteImport } from './routes/basic/index'
import { Route as FigmaProfileRouteImport } from './routes/figma/profile'
import { Route as FigmaMapRouteImport } from './routes/figma/map'
import { Route as FigmaExploreRouteImport } from './routes/figma/explore'
import { Route as FigmaLayoutRouteImport } from './routes/figma/_layout'
import { Route as DevProfileRouteImport } from './routes/dev/profile'
import { Route as DevMapRouteImport } from './routes/dev/map'
import { Route as DevMaldyRouteImport } from './routes/dev/maldy'
import { Route as DevExploreRouteImport } from './routes/dev/explore'
import { Route as BasicAboutRouteImport } from './routes/basic/about'
import { Route as BasicLayoutRouteImport } from './routes/basic/_layout'
import { Route as BasicMaldyIndexRouteImport } from './routes/basic/maldy/index'
import { Route as BasicExperiencesIndexRouteImport } from './routes/basic/experiences/index'
import { Route as DevActivitiesIdRouteImport } from './routes/dev/activities/$id'
import { Route as BasicExperiencesNewRouteImport } from './routes/basic/experiences/new'

const FigmaRouteImport = createFileRoute('/figma')()
const BasicRouteImport = createFileRoute('/basic')()

const FigmaRoute = FigmaRouteImport.update({
  id: '/figma',
  path: '/figma',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicRoute = BasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const FigmaIndexRoute = FigmaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FigmaRoute,
} as any)
const BasicIndexRoute = BasicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BasicRoute,
} as any)
const FigmaProfileRoute = FigmaProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FigmaRoute,
} as any)
const FigmaMapRoute = FigmaMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => FigmaRoute,
} as any)
const FigmaExploreRoute = FigmaExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => FigmaRoute,
} as any)
const FigmaLayoutRoute = FigmaLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => FigmaRoute,
} as any)
const DevProfileRoute = DevProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DevRoute,
} as any)
const DevMapRoute = DevMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DevRoute,
} as any)
const DevMaldyRoute = DevMaldyRouteImport.update({
  id: '/maldy',
  path: '/maldy',
  getParentRoute: () => DevRoute,
} as any)
const DevExploreRoute = DevExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => DevRoute,
} as any)
const BasicAboutRoute = BasicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => BasicRoute,
} as any)
const BasicLayoutRoute = BasicLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => BasicRoute,
} as any)
const BasicMaldyIndexRoute = BasicMaldyIndexRouteImport.update({
  id: '/maldy/',
  path: '/maldy/',
  getParentRoute: () => BasicRoute,
} as any)
const BasicExperiencesIndexRoute = BasicExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => BasicRoute,
} as any)
const DevActivitiesIdRoute = DevActivitiesIdRouteImport.update({
  id: '/activities/$id',
  path: '/activities/$id',
  getParentRoute: () => DevRoute,
} as any)
const BasicExperiencesNewRoute = BasicExperiencesNewRouteImport.update({
  id: '/experiences/new',
  path: '/experiences/new',
  getParentRoute: () => BasicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dev': typeof DevRouteWithChildren
  '/basic': typeof BasicLayoutRoute
  '/basic/about': typeof BasicAboutRoute
  '/dev/explore': typeof DevExploreRoute
  '/dev/maldy': typeof DevMaldyRoute
  '/dev/map': typeof DevMapRoute
  '/dev/profile': typeof DevProfileRoute
  '/figma': typeof FigmaLayoutRoute
  '/figma/explore': typeof FigmaExploreRoute
  '/figma/map': typeof FigmaMapRoute
  '/figma/profile': typeof FigmaProfileRoute
  '/basic/': typeof BasicIndexRoute
  '/figma/': typeof FigmaIndexRoute
  '/basic/experiences/new': typeof BasicExperiencesNewRoute
  '/dev/activities/$id': typeof DevActivitiesIdRoute
  '/basic/experiences': typeof BasicExperiencesIndexRoute
  '/basic/maldy': typeof BasicMaldyIndexRoute
}
export interface FileRoutesByTo {
  '/dev': typeof DevRouteWithChildren
  '/basic': typeof BasicIndexRoute
  '/basic/about': typeof BasicAboutRoute
  '/dev/explore': typeof DevExploreRoute
  '/dev/maldy': typeof DevMaldyRoute
  '/dev/map': typeof DevMapRoute
  '/dev/profile': typeof DevProfileRoute
  '/figma': typeof FigmaIndexRoute
  '/figma/explore': typeof FigmaExploreRoute
  '/figma/map': typeof FigmaMapRoute
  '/figma/profile': typeof FigmaProfileRoute
  '/basic/experiences/new': typeof BasicExperiencesNewRoute
  '/dev/activities/$id': typeof DevActivitiesIdRoute
  '/basic/experiences': typeof BasicExperiencesIndexRoute
  '/basic/maldy': typeof BasicMaldyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dev': typeof DevRouteWithChildren
  '/basic': typeof BasicRouteWithChildren
  '/basic/_layout': typeof BasicLayoutRoute
  '/basic/about': typeof BasicAboutRoute
  '/dev/explore': typeof DevExploreRoute
  '/dev/maldy': typeof DevMaldyRoute
  '/dev/map': typeof DevMapRoute
  '/dev/profile': typeof DevProfileRoute
  '/figma': typeof FigmaRouteWithChildren
  '/figma/_layout': typeof FigmaLayoutRoute
  '/figma/explore': typeof FigmaExploreRoute
  '/figma/map': typeof FigmaMapRoute
  '/figma/profile': typeof FigmaProfileRoute
  '/basic/': typeof BasicIndexRoute
  '/figma/': typeof FigmaIndexRoute
  '/basic/experiences/new': typeof BasicExperiencesNewRoute
  '/dev/activities/$id': typeof DevActivitiesIdRoute
  '/basic/experiences/': typeof BasicExperiencesIndexRoute
  '/basic/maldy/': typeof BasicMaldyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dev'
    | '/basic'
    | '/basic/about'
    | '/dev/explore'
    | '/dev/maldy'
    | '/dev/map'
    | '/dev/profile'
    | '/figma'
    | '/figma/explore'
    | '/figma/map'
    | '/figma/profile'
    | '/basic/'
    | '/figma/'
    | '/basic/experiences/new'
    | '/dev/activities/$id'
    | '/basic/experiences'
    | '/basic/maldy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dev'
    | '/basic'
    | '/basic/about'
    | '/dev/explore'
    | '/dev/maldy'
    | '/dev/map'
    | '/dev/profile'
    | '/figma'
    | '/figma/explore'
    | '/figma/map'
    | '/figma/profile'
    | '/basic/experiences/new'
    | '/dev/activities/$id'
    | '/basic/experiences'
    | '/basic/maldy'
  id:
    | '__root__'
    | '/dev'
    | '/basic'
    | '/basic/_layout'
    | '/basic/about'
    | '/dev/explore'
    | '/dev/maldy'
    | '/dev/map'
    | '/dev/profile'
    | '/figma'
    | '/figma/_layout'
    | '/figma/explore'
    | '/figma/map'
    | '/figma/profile'
    | '/basic/'
    | '/figma/'
    | '/basic/experiences/new'
    | '/dev/activities/$id'
    | '/basic/experiences/'
    | '/basic/maldy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DevRoute: typeof DevRouteWithChildren
  BasicRoute: typeof BasicRouteWithChildren
  FigmaRoute: typeof FigmaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/figma': {
      id: '/figma'
      path: '/figma'
      fullPath: '/figma'
      preLoaderRoute: typeof FigmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic': {
      id: '/basic'
      path: '/basic'
      fullPath: '/basic'
      preLoaderRoute: typeof BasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figma/': {
      id: '/figma/'
      path: '/'
      fullPath: '/figma/'
      preLoaderRoute: typeof FigmaIndexRouteImport
      parentRoute: typeof FigmaRoute
    }
    '/basic/': {
      id: '/basic/'
      path: '/'
      fullPath: '/basic/'
      preLoaderRoute: typeof BasicIndexRouteImport
      parentRoute: typeof BasicRoute
    }
    '/figma/profile': {
      id: '/figma/profile'
      path: '/profile'
      fullPath: '/figma/profile'
      preLoaderRoute: typeof FigmaProfileRouteImport
      parentRoute: typeof FigmaRoute
    }
    '/figma/map': {
      id: '/figma/map'
      path: '/map'
      fullPath: '/figma/map'
      preLoaderRoute: typeof FigmaMapRouteImport
      parentRoute: typeof FigmaRoute
    }
    '/figma/explore': {
      id: '/figma/explore'
      path: '/explore'
      fullPath: '/figma/explore'
      preLoaderRoute: typeof FigmaExploreRouteImport
      parentRoute: typeof FigmaRoute
    }
    '/figma/_layout': {
      id: '/figma/_layout'
      path: '/figma'
      fullPath: '/figma'
      preLoaderRoute: typeof FigmaLayoutRouteImport
      parentRoute: typeof FigmaRoute
    }
    '/dev/profile': {
      id: '/dev/profile'
      path: '/profile'
      fullPath: '/dev/profile'
      preLoaderRoute: typeof DevProfileRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/map': {
      id: '/dev/map'
      path: '/map'
      fullPath: '/dev/map'
      preLoaderRoute: typeof DevMapRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/maldy': {
      id: '/dev/maldy'
      path: '/maldy'
      fullPath: '/dev/maldy'
      preLoaderRoute: typeof DevMaldyRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/explore': {
      id: '/dev/explore'
      path: '/explore'
      fullPath: '/dev/explore'
      preLoaderRoute: typeof DevExploreRouteImport
      parentRoute: typeof DevRoute
    }
    '/basic/about': {
      id: '/basic/about'
      path: '/about'
      fullPath: '/basic/about'
      preLoaderRoute: typeof BasicAboutRouteImport
      parentRoute: typeof BasicRoute
    }
    '/basic/_layout': {
      id: '/basic/_layout'
      path: '/basic'
      fullPath: '/basic'
      preLoaderRoute: typeof BasicLayoutRouteImport
      parentRoute: typeof BasicRoute
    }
    '/basic/maldy/': {
      id: '/basic/maldy/'
      path: '/maldy'
      fullPath: '/basic/maldy'
      preLoaderRoute: typeof BasicMaldyIndexRouteImport
      parentRoute: typeof BasicRoute
    }
    '/basic/experiences/': {
      id: '/basic/experiences/'
      path: '/experiences'
      fullPath: '/basic/experiences'
      preLoaderRoute: typeof BasicExperiencesIndexRouteImport
      parentRoute: typeof BasicRoute
    }
    '/dev/activities/$id': {
      id: '/dev/activities/$id'
      path: '/activities/$id'
      fullPath: '/dev/activities/$id'
      preLoaderRoute: typeof DevActivitiesIdRouteImport
      parentRoute: typeof DevRoute
    }
    '/basic/experiences/new': {
      id: '/basic/experiences/new'
      path: '/experiences/new'
      fullPath: '/basic/experiences/new'
      preLoaderRoute: typeof BasicExperiencesNewRouteImport
      parentRoute: typeof BasicRoute
    }
  }
}

interface DevRouteChildren {
  DevExploreRoute: typeof DevExploreRoute
  DevMaldyRoute: typeof DevMaldyRoute
  DevMapRoute: typeof DevMapRoute
  DevProfileRoute: typeof DevProfileRoute
  DevActivitiesIdRoute: typeof DevActivitiesIdRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevExploreRoute: DevExploreRoute,
  DevMaldyRoute: DevMaldyRoute,
  DevMapRoute: DevMapRoute,
  DevProfileRoute: DevProfileRoute,
  DevActivitiesIdRoute: DevActivitiesIdRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface BasicRouteChildren {
  BasicLayoutRoute: typeof BasicLayoutRoute
  BasicAboutRoute: typeof BasicAboutRoute
  BasicIndexRoute: typeof BasicIndexRoute
  BasicExperiencesNewRoute: typeof BasicExperiencesNewRoute
  BasicExperiencesIndexRoute: typeof BasicExperiencesIndexRoute
  BasicMaldyIndexRoute: typeof BasicMaldyIndexRoute
}

const BasicRouteChildren: BasicRouteChildren = {
  BasicLayoutRoute: BasicLayoutRoute,
  BasicAboutRoute: BasicAboutRoute,
  BasicIndexRoute: BasicIndexRoute,
  BasicExperiencesNewRoute: BasicExperiencesNewRoute,
  BasicExperiencesIndexRoute: BasicExperiencesIndexRoute,
  BasicMaldyIndexRoute: BasicMaldyIndexRoute,
}

const BasicRouteWithChildren = BasicRoute._addFileChildren(BasicRouteChildren)

interface FigmaRouteChildren {
  FigmaLayoutRoute: typeof FigmaLayoutRoute
  FigmaExploreRoute: typeof FigmaExploreRoute
  FigmaMapRoute: typeof FigmaMapRoute
  FigmaProfileRoute: typeof FigmaProfileRoute
  FigmaIndexRoute: typeof FigmaIndexRoute
}

const FigmaRouteChildren: FigmaRouteChildren = {
  FigmaLayoutRoute: FigmaLayoutRoute,
  FigmaExploreRoute: FigmaExploreRoute,
  FigmaMapRoute: FigmaMapRoute,
  FigmaProfileRoute: FigmaProfileRoute,
  FigmaIndexRoute: FigmaIndexRoute,
}

const FigmaRouteWithChildren = FigmaRoute._addFileChildren(FigmaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DevRoute: DevRouteWithChildren,
  BasicRoute: BasicRouteWithChildren,
  FigmaRoute: FigmaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
