/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaldyIndexRouteImport } from './routes/maldy/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences/index'
import { Route as ExperiencesNewRouteImport } from './routes/experiences/new'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaldyIndexRoute = MaldyIndexRouteImport.update({
  id: '/maldy/',
  path: '/maldy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesNewRoute = ExperiencesNewRouteImport.update({
  id: '/experiences/new',
  path: '/experiences/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/maldy': typeof MaldyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/maldy': typeof MaldyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/maldy/': typeof MaldyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/experiences/new' | '/experiences' | '/maldy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/experiences/new' | '/experiences' | '/maldy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/experiences/new'
    | '/experiences/'
    | '/maldy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExperiencesNewRoute: typeof ExperiencesNewRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
  MaldyIndexRoute: typeof MaldyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maldy/': {
      id: '/maldy/'
      path: '/maldy'
      fullPath: '/maldy'
      preLoaderRoute: typeof MaldyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/new': {
      id: '/experiences/new'
      path: '/experiences/new'
      fullPath: '/experiences/new'
      preLoaderRoute: typeof ExperiencesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExperiencesNewRoute: ExperiencesNewRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
  MaldyIndexRoute: MaldyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
